If:
  PathMatch: /home/gtc/esp/esp-idf/.*
CompileFlags:
  CompilationDatabase: /home/gtc/Desktop/workspace/NEMA2000_ESP/build
  Remove:
    - --target=*
    - -mlongcalls
    - -fno-shrink-wrap
    - -fstrict-volatile-bitfields
    - -fno-tree-switch-conversion
---
If:
  PathMatch: /home/gtc/esp/esp-idf/.*\.(c|h)$
CompileFlags:
  Compiler: /home/gtc/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20260121/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc
---
If:
  PathMatch: /home/gtc/esp/esp-idf/.*\.(cpp|hpp|hh|hxx)$
CompileFlags:
  Compiler: /home/gtc/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20260121/xtensa-esp-elf/bin/xtensa-esp32-elf-g++
